print("This is a Travel Guide. Please fill out the following blanks.")
noun = input("What is a noun?")
adjective = input("What is a adjective")
another_adjective = input("What is another adjective")
verb = input("What is a verb")
another_noun = input("What is another noun")
another_verb = input("What is another verb")
another_another_verb = input("What is another verb.")
input("Press enter to continue")
print("f The great city of {noun},")
print(f"is a very {adjective} place.")
print(f"The people there are very {another_adjective}.")
print(f"But there are still people who like to {verb}.")
print(f"In the center of the city there is a giant statue of {another_noun}.")
print("A lot of people like to go there.")
print(f"I really suggest you {another_verb} there.")
print(f"Now finnaly the top thing to do in downtown is to {another_another_verb}.")
print(f"Hopefully a lot of people use this travel guide to vist the Great City of {noun}.")
print("Thank You")