print(r".----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.          .----------------.  .----------------.  .----------------.  .----------------.  .----------------. ")
print(r".--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------.  |     | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |")
print(r" | |  _   _  |  | || | |_   __ \    | || |     /  \     | || ||_  _| |_  _| | || | |_   ___  |  | || |  |_   _|     | |     | |  .' ___  |   | || ||_   _||_   _|| || |    |_   _|   | || | |_   ___ `.  | || | |_   ___  |  | |")
print(r" | |_/ | | \_|  | || |   | |__) |   | || |    / /\ \    | || |  \ \   / /   | || |   | |_  \_|  | || |    | |       | |     | | / .'   \_|   | || |  | |    | |  | || |      | |     | || |   | |   `. \ | || |   | |_  \_|  | |")
print(r" |     | |      | || |   |  __ /    | || |   / ____ \   | || |   \ \ / /    | || |   |  _|  _   | || |    | |   _   | |     | | | |    ____  | || |  | '    ' |  | || |      | |     | || |   | |    | | | || |   |  _|  _   | |")
print(r" |    _| |_     | || |  _| |  \ \_  | || | _/ /    \ \_ | || |    \ ' /     | || |  _| |___/ |  | || |   _| |__/ |  | |     | | \ `.___]  _| | || |   \ `--' /   | || |     _| |_    | || |  _| |___.' / | || |  _| |___/ |  | |")
print(r" |   |_____|    | || | |____| |___| | || ||____|  |____|| || |     \_/      | || | |_________|  | || |  |________|  | |     | |  `._____.'   | || |    `.__.'    | || |    |_____|   | || | |________.'  | || | |_________|  | |")
print(r" |              | || |              | || |              | || |              | || |              | || |              | |     | |              | || |              | || |              | || |              | || |              | |")
print(r" '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |     | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |")
print(r"'----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'         '----------------'  '----------------'  '----------------'  '----------------'  '----------------' ")
print("This is a Travel Guide Madlibs. Please fill out the following blanks.")
noun = input("Give me a noun")
adjective = input("Give me an adjective")
another_adjective = input("Give me another adjective")
verb = input("Give me a verb")
another_noun = input("Give me another noun")
another_verb = input("Give me another verb")
another_another_verb = input("Give me another verb")
input("Press enter to continue")
print(f" The great city of{noun},")
print(f"is a very{adjective} place.")
print(f"The people there are very{another_adjective}.")
print(f"But there are still people who like to{verb}.")
print(f"In the center of the city there is a giant statue of{another_noun}.")
print("A lot of people like to go there.")
print(f"I really suggest you{another_verb} there.")
print(f"Now finally the top thing to do in downtown is to{another_another_verb}.")
print(f"Hopefully a lot of people use this travel guide to vist the Great City of{noun}.")
print("Thank You")